services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: regncon-image
    # tty required by air
    tty: true
    ports:
      - 7331:7331
      - 8080:8080
    volumes:
      - type: bind
        source: ./src/
        target: /home/devuser/app
        read_only: false