// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/Regncon/conorganizer/models"
	"github.com/Regncon/conorganizer/utils"
)

func EditEvent(event models.Event) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style type=\"text/css\">\r\n\t\t\tlegend {\r\n\t\t\t\tbackground-color: #4b4b4b;\r\n\t\t\t\tpadding: 3px 6px;\r\n\t\t\t\tborder-radius: 1rem;\r\n\t\t\t}\r\n\r\n\t\t\tinput {\r\n\t\t\t\tmargin: 0.4rem;\r\n\t\t\t}\r\n\t\t\t.button {\r\n\t\t\t\tdisplay: inline-block;\r\n\t\t\t\tpadding: 12px 28px;\r\n\t\t\t\tmargin: 10px;\r\n\t\t\t\tfont-size: 24px;\r\n\t\t\t\tfont-weight: bold;\r\n\t\t\t\ttext-transform: uppercase;\r\n\t\t\t\tcolor: #fff;\r\n\t\t\t\tbackground-image: linear-gradient(to bottom right, #00c6ff, #0072ff);\r\n\t\t\t\tborder: none;\r\n\t\t\t\tborder-radius: 40px;\r\n\t\t\t\tbox-shadow: 0px 4px 0px #0072ff;\r\n\t\t\t\ttransition: all 0.2s ease-in-out;\r\n\t\t\t\tcursor: pointer;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t.button:hover {\r\n\t\t\t\ttransform: translateY(-2px);\r\n\t\t\t\tbox-shadow: 0px 6px 0px #0072ff;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t.button:active {\r\n\t\t\t\ttransform: translateY(0px);\r\n\t\t\t\tbox-shadow: none;\r\n\t\t\t\tbackground-image: linear-gradient(to bottom right, #0072ff, #00c6ff);\r\n\t\t\t\t}\r\n\r\n\t\t\t\t.button:before,\r\n\t\t\t\t.button:after {\r\n\t\t\t\tcontent: \"\";\r\n\t\t\t\tposition: absolute;\r\n\t\t\t\twidth: 0;\r\n\t\t\t\theight: 0;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t.button:before {\r\n\t\t\t\ttop: -3px;\r\n\t\t\t\tleft: -3px;\r\n\t\t\t\tborder-radius: 40px;\r\n\t\t\t\tborder-top: 3px solid #fff;\r\n\t\t\t\tborder-left: 3px solid #fff;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t.button:after {\r\n\t\t\t\tbottom: -3px;\r\n\t\t\t\tright: -3px;\r\n\t\t\t\tborder-radius: 40px;\r\n\t\t\t\tborder-bottom: 3px solid #fff;\r\n\t\t\t\tborder-right: 3px solid #fff;\r\n\t\t\t}\r\n\r\n\t\t</style><div id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("editId%d", event.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editEvent.templ`, Line: 73, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><button class=\"button\" data-on-click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("@put('/event/%s/save')", utils.NumberToString(event.ID)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editEvent.templ`, Line: 75, Col: 110}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">Save</button> <button class=\"button\" data-on-click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("@put('/event/cancel')")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editEvent.templ`, Line: 76, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Cancel</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
