// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Ternary(condition bool) string {
	if condition {
		return "true"
	}
	return "false"
}

func EditButton(id int, isEditing bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\n\t\t.button2 {\n\t\t\tposition: relative;\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tjustify-content: flex-start;\n\t\t\twidth: 6.25rem;\n\t\t\theight: 3.25rem;\n\t\t\tborder: none;\n\t\t\tpadding: 0px 20px;\n\t\t\tbackground-color: rgb(168, 38, 255);\n\t\t\tcolor: white;\n\t\t\tfont-weight: 500;\n\t\t\tcursor: pointer;\n\t\t\tborder-radius: 10px;\n\t\t\tbox-shadow: 5px 5px 0px rgb(140, 32, 212);\n\t\t\ttransition-duration: .3s;\n\t\t}\n\n\t\t.svg {\n\t\t\twidth: 13px;\n\t\t\tposition: absolute;\n\t\t\tright: 0;\n\t\t\tmargin-right: 20px;\n\t\t\tfill: transparent;\n\t\t\ttransition-duration: .3s;\n\t\t}\n\n\t\t.button2:hover {\n\t\t\tcolor: transparent;\n\t\t}\n\n\t\t.button2:hover svg {\n\t\t\tright: 43%;\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t\tborder: none;\n\t\t\ttransition-duration: .3s;\n\t\t}\n\n\t\t.button2:active {\n\t\t\ttransform: translate(3px , 3px);\n\t\t\ttransition-duration: .3s;\n\t\t\tbox-shadow: 2px 2px 0px rgb(140, 32, 212);\n\t\t}\n\t\t.button2:disabled {\n\t\t\tcursor: not-allowed;\n\t\t}\n\t</style><button data-on-click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("@put('/event/%d/edit')", id))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/editButton.templ`, Line: 64, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"button2\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isEditing {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " disabled")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">edit <svg class=\"svg\" viewBox=\"0 0 24 24\"><g fill=\"currentColor\" stroke=\"#000\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"><path stroke-dasharray=\"56\" stroke-dashoffset=\"56\" d=\"M3 21l2 -6l11 -11c1 -1 3 -1 4 0c1 1 1 3 0 4l-11 11l-6 2\"><animate fill=\"freeze\" attributeName=\"stroke-dashoffset\" dur=\"0.6s\" values=\"56;0\"></animate></path> <path stroke-dasharray=\"8\" stroke-dashoffset=\"8\" d=\"M15 5l4 4\"><animate fill=\"freeze\" attributeName=\"stroke-dashoffset\" begin=\"0.6s\" dur=\"0.2s\" values=\"8;0\"></animate></path> <path stroke-dasharray=\"6\" stroke-dashoffset=\"6\" stroke-width=\"1\" d=\"M6 15l3 3\"><animate fill=\"freeze\" attributeName=\"stroke-dashoffset\" begin=\"0.6s\" dur=\"0.2s\" values=\"6;0\"></animate></path></g></svg></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
