version: "3"

env:
  STATIC_DIR: "public"

tasks:
  # The `build:` tasks below are used together for "production" builds of your project
  build:
    cmds:
      - go build -o bin/main .
    deps:
      - build:templ
    parallel: true

  build:templ:
    cmds:
      - go run templ generate -v

  # The `dev:` tasks below are used together for "dev" builds, and will hot-reload your entire project when there are code changes
  dev:
    deps:
      - dev/air

  dev/air:
    cmds:
      - air

  dev/templ:
    cmds:
      - templ generate --watch --proxybind="0.0.0.0" --proxy="http://localhost:8080" --open-browser=false -v

  # Use this task to debug your project with the delve debugger
  debug:
    cmds:
      - go run github.com/go-delve/delve/cmd/dlv@v1.23.1 exec ./bin/main
    deps:
      - build

  # What does this do?
  run:
    cmds:
      - ./bin/main
    deps:
      - build
